### ISSUE TITLE
Management of Cluster Partitions

### ISSUE THREAD

**Issue by schofield** [humio/humio-operator#12]
Use standard AZ annotations
Rack awareness
Ingest
Storage and bucket storage

**Comment by SaaldjorMike** [comment]
Need to add a flag that enables logic in the operator to balance out partitions. This flag should be disable by default.

**Comment by SaaldjorMike** [comment]
I'm going to close this issue. We've recently added support into Humio so it can suggest partition layouts, and recently added the support in the humio-operator to leverage the suggested partition layouts from Humio, which takes availability zone into account when making suggestions: https://github.com/humio/humio-operator/pull/284

We still need to do a bit of work related to scale down, but we already have a separate issue for tracking that: https://github.com/humio/humio-operator/issues/179
