### ISSUE TITLE
Resources - Cluster logging and metrics

### ISSUE THREAD

**Issue by schofield** [humio/humio-operator#14]

**Comment by SaaldjorMike** [comment]
As for signals from the operator itself I think we have a couple of things already:
- logs: output in JSON format and should be straightforward to use.
- metrics: currently we only have a few metrics that shows how many of the different resource types the operator creates.
- additional columns when listing humio clusters: https://github.com/humio/humio-operator/blob/master/pkg/apis/core/v1alpha1/humiocluster_types.go#L77-L79

If we want to keep log shipping and metric collection out of this project (which I agree with) and just keep them in the existing helm chart, I'm not sure how much more we have to fix on this one.

Perhaps we should consider closing this issue? @jswoods @schofield

**Comment by schofield** [comment]
works for me
