### ISSUE TITLE
Being able to configure path or documenting nginx rewrite rules for using alternate URL prefixes

### ISSUE THREAD

**Issue by andrem123456** [humio/humio-operator#152]
I would like to access my humio URL using a different URL prefix. Changing the `path` in the humio operator didn't work but this is probably possible using nginx rewrite rules.

> `nginx.ingress.kubernetes.io/rewrite-target`
> annotation to achieve the /logs path, documentation for that annotation is available here: https://kubernetes.github.io/ingress-nginx/examples/rewrite/
> 

Issue to track either documenting rewrite rule or adding support for the `path` in the Humio Operator. Preferabbly being able to do via the `path` in Humio operator would be ideal

**Comment by nevosial** [comment]
Please note even if we use the rewrite rules; we cannot achieve the desired result.

As we try to hit the <host-name>/logs  --> `The repository 'logs' might actually exist but you lack permission to access it. If the URL seems correct, try logging in as another user or get a repository admin to grant you access.` 
Clicking on the `Go to front page` button redirects to the <host-name> i.e Humio UI.
