### ISSUE TITLE
Bugs/improvements to auth sidecar

### ISSUE THREAD

**Issue by SaaldjorMike** [humio/humio-operator#175]
- [x] Ensure auth sidecar works in a multi-org setup https://github.com/humio/humio-operator/pull/186 & https://github.com/humio/humio-operator/pull/189
- [ ] Move away from parsing global inside the sidecar https://github.com/humio/humio-operator/pull/247
- [x] Consider options so we do not rely on cluster DNS https://github.com/humio/humio-operator/pull/183

**Comment by kaspernissen** [comment]
We are currently evaluating linkerd in a multi cluster setup with humio running in a centralized cluster. However, when we inject the linkerd-proxy to the humio-core pods, the auth container is not able to talk to humio. It seems that the cluster DNS resolution fails for some reason. It would be awesome as suggested in this issue that the auth container talks directly with humio over localhost. 

Error log from auth:
```
got err trying to obtain user ID of admin user: Post "https://humio-core-scmhkf.humio.logging:8080/graphql": dial tcp: lookup humio-core-scmhkf.humio.logging on 100.64.0.10:53: no such host
got err trying to obtain user ID of admin user: Post "https://humio-core-scmhkf.humio.logging:8080/graphql": dial tcp: lookup humio-core-scmhkf.humio.logging on 100.64.0.10:53: no such host
```
