### ISSUE TITLE
Allow user-defined annotations for pods

### ISSUE THREAD

**Issue by SaaldjorMike** [humio/humio-operator#203]
A user should be able to specify additional pod annotations. This makes it possible to e.g. mark pods for service mesh injection and such.

**Comment by kaspernissen** [comment]
We have a use case, where we need to add specific annotations to the pods created by the operator. We are currently trying to add humio to a service mesh (linkerd).

Currently, we have enabled proxy injection on the namespace level, however, for this specific use case we don't want all pods in this namespace to be part of the mesh. It would therefore be awesome to be able to specify custom annotations for the humio-core pods, e.g. `linkerd.io/inject: enabled` or specific configurations for the linkerd proxies for humio.
