### ISSUE TITLE
Feature Request: CRD for HumioViews

### ISSUE THREAD

**Issue by kaspernissen** [humio/humio-operator#207]
It would be awesome to be able to manage views in Humio through a custom resource, e.g. `HumioView`.

**Comment by kaspernissen** [comment]
@jswoods @SaaldjorMike are you planning on implementing this one anytime soon? Otherwise, we would like to take a stab at it. 👍

**Comment by SaaldjorMike** [comment]
@kaspernissen I don't think we are close to starting the work on this soon, at least not for multiple weeks. Most of the focus has been on the HumioCluster resource type.

As for adding support for views, we _may_ need to extend the [api package in humio/cli](https://github.com/humio/cli/tree/master/api) project in case what we need is not available right now to add support for views.

**Comment by kaspernissen** [comment]
Yes, it looks like it's read-only at the moment with `Get` and `List`. 

We will have a look at it, it should be fairly simple to add support for it as the graphql already has support creating views, right?

**Comment by SaaldjorMike** [comment]
> We will have a look at it, it should be fairly simple to add support for it as the graphql already has support creating views, right?

That would be my expectation yes, at least as long as we keep RBAC out of the picture. Right now repositories created by the operator does not allow you to specify what users/groups gets access to the repository, and I suppose we could consider skipping RBAC for views in the first iteration as well. I guess it all depends on the amount of work that is required to make RBAC work.

**Comment by mahlunar** [comment]
Hi. I have forked the repository and have begun working on it in collaboration with @kaspernissen.

@SaaldjorMike You are right. The cli needs an update which is where we will start.
