### ISSUE TITLE
Feature Request: CRD for HumioAlertNotifier

### ISSUE THREAD

**Issue by kaspernissen** [humio/humio-operator#208]
It would be awesome to be able to manage notifiers for alerts in Humio through a custom resource, e.g. `HumioAlertNotifier`.

**Comment by daviddeng2100** [comment]
👍

**Comment by SaaldjorMike** [comment]
"Alert notifiers" has been renamed to "actions" and this was fixed in https://github.com/humio/humio-operator/pull/338
