### ISSUE TITLE
Generic node pools

### ISSUE THREAD

**Issue by SaaldjorMike** [humio/humio-operator#253]
We need to add support for adding "node pools" which means humio pods with a common configuration. This have to make it possible to enable a feature only on a subset of the nodes, namely those in a specific node pool.

Either:
- expand HumioCluster CRD with a list of node pool and configurations for each node pool
- or, add a dedicated CRD so you create a CR per node pool.

**Comment by jswoods** [comment]
Fixed by https://github.com/humio/humio-operator/pull/508.
