### ISSUE TITLE
Deploying v. 0.2.0 yields an error: humioclusters.core.humio.com CRD has invalid spec.preserveUnknownFields

### ISSUE THREAD

**Issue by mahlunar** [humio/humio-operator#267]
When we deploy v. 0.2.0 we get the following error:

The CustomResourceDefinition \"humioclusters.core.humio.com\" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema"

We deploy using Flux: 1.20.2 which uses kubectl: 1.17.11
Kubernetes Cluster Version: 1.18

I also tried with kubectl version: v.1.18.10. Same error.

**Comment by Crevil** [comment]
Is this an added field? In that case we can replace the resource in the cluster directly with kubectl and then let flux take control of it afterwards.

**Comment by jswoods** [comment]
@mahlunar - can you verify which CRD you are applying? We do not currently set `spec.preserveUnknownFields` so I'm not sure why it would be complaining about it being set. 

Looking at https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#field-pruning, it was set in `apiextensions.k8s.io/v1beta1` but now we are using `apiextensions.k8s.io/v1`. 

I couldn't reproduce this by applying the 0.2.0 CRD which uses `apiextensions.k8s.io/v1`:
```
kubectl apply -f https://raw.githubusercontent.com/humio/humio-operator/operator-0.2.0/config/crd/bases/core.humio.com_humioclusters.yaml
customresourcedefinition.apiextensions.k8s.io/humioclusters.core.humio.com configured
```

But I do get this error if I apply an older CRD that uses `apiextensions.k8s.io/v1beta1`:
```
kubectl apply -f https://raw.githubusercontent.com/humio/humio-operator/operator-0.0.14/config/crd/bases/core.humio.com_humioclusters.yaml
The CustomResourceDefinition "humioclusters.core.humio.com" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema
```

That field pruning doc also mentions the field may be set to true following the conversion of the CRD, though I'm not clear why it wouldn't be overwritten when the updated CRD is applied. You can check this by running `kubectl get crd humioclusters.core.humio.com -o template --template {{.spec.preserveUnknownFields}}`. If that returns true, then I believe you'll need to edit the existing CRD and remove that field.

**Comment by mahlunar** [comment]
Thanks for the reply. It was as you suggested. We replaced the CRD and it worked like a charm.
