### ISSUE TITLE
Update to 0.2.0 results in "invalid: spec.preserveUnknownFields: "

### ISSUE THREAD

**Issue by estahn** [humio/humio-operator#273]
```
CustomResourceDefinition.apiextensions.k8s.io "humioclusters.core.humio.com" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema
```
![image](https://user-images.githubusercontent.com/362174/99386215-3931e780-2926-11eb-8d8a-32348e24729f.png)

**Comment by SaaldjorMike** [comment]
This looks like the same thing as in #267 
Perhaps you could take a quick look at that one and see if that helps out here?

**Comment by estahn** [comment]
duplicate of #267 

```
kubectl edit crd humioclusters.core.humio.com
```

and removing `spec.preserveUnknownFields` fixed it.
