### ISSUE TITLE
Feature Request: HumioAlert 

### ISSUE THREAD

**Issue by kaspernissen** [humio/humio-operator#296]
Similar to this PR on HumioAlertNotifiers (https://github.com/humio/humio-operator/issues/208) it would be incredibly powerful, to allow users to create alerts using CRDs, similar to how the prometheus-operator does this with `PrometheusRule`. https://github.com/prometheus-operator/prometheus-operator/blob/master/example/user-guides/alerting/prometheus-example-rules.yaml

This would allow developers (at least in our case) to have prometheus alerts and humio alerts defined in one place, in git. It would also allow us to provide our developers with some default alerts configured when e.g. creating a new service.

**Comment by nevosial** [comment]
This is what we do too today using git, yaml and humio-apis; but would be great addition to the operator if we can create alerts/notifiers using CRDs.

**Comment by SaaldjorMike** [comment]
Fixed by https://github.com/humio/humio-operator/pull/338
