### ISSUE TITLE
Add support for role-permissions.json

### ISSUE THREAD

**Issue by SaaldjorMike** [humio/humio-operator#321]
Similar to what we do with view-group-permissions.json, but there is a newer way to configure permissions which is based on role-permissions.json: https://docs.humio.com/docs/security/roles/

Workaround until this is implemented similar to `viewGroupPermissions` is to use `extraVolumes` and `extraVolumeMounts` to append entries to the pod spec field `volumes` and humio container spec field `volumeMounts`.

**Comment by Crevil** [comment]
This would be a nice addition. Are there anything blocking this or could we maybe go ahead and provide a PR for it?

If it is just to made like the `viewGroupPermissions` then it seems straight forward.

**Comment by Crevil** [comment]
Further more the workaround mentioned. I'm having a hard time figuring out where to mount the file.

The docs mentions this at https://library.humio.com/cloud/docs/security/authorization/#authorization-roles-files

> The file must be named role-permissions.json and located in ‘humio-data/’

I expected this to be the absolute path `/humio-data/role-permissions.json` is that correct?

**Comment by SaaldjorMike** [comment]
Fixed by https://github.com/humio/humio-operator/pull/702
