### ISSUE TITLE
HumioView CR creation fails without any hints

### ISSUE THREAD

**Issue by mahlunar** [humio/humio-operator#352]
Currently, when creating a HumioView custom resource, the creation can fail when calling the Humio API.

If the input is invalid then the following would be logged:
```
could not create view: There were errors in the input.
``` 
In our case we tried to create a view with a connection to a non-existant repository by mistake.

It would be great if the log would give a hint on what went wrong 🙏🏼 

Humio operator version: 0.4.0
Humio cluster version: 1.20.4

**Comment by SaaldjorMike** [comment]
The changes that was merged today for GraphQL client means we'll going forward also be logging the additional context when this happens.
