### ISSUE TITLE
Humio Service should be headless.

### ISSUE THREAD

**Issue by anas-aso** [humio/humio-operator#370]
The external URL for Humio pods is defined by `EXTERNAL_URL` https://github.com/humio/humio-operator/blob/dc75e6f068a95f6020861f19095c8a1be16d3344/controllers/humiocluster_defaults.go#L386

This URL is not resolvable unless the service exposing Humio pods is headless.
I had to force the recreation of the service as headless to get rid of an error/warning on Humio UI complaining that the other pods are not responding.

**Comment by jswoods** [comment]
@anas-aso - We are not currently running headless services on any of our clusters. The DNS resolution is done by using subdomain set on each pod as per https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields. I would like to understand why that is not working for you. Could you send me the dns implementation you are using (kubedns, coredns, etc) and version of that, along with the kubernetes version? Could you also check what the subdomain is set to on each pod? It should be the HumioCluster name, and should also be the same name as the service.
