### ISSUE TITLE
auth container  has /data/humio-data  mounted as readonly

### ISSUE THREAD

**Issue by MarioSchuerewegen** [humio/humio-operator#420]
i cant install using humio-operator 0.10.1
the core pods keep crashing
**_ auth Waiting on the Humio container to create the files /data/humio-data/local-admin-token.txt and /data/humio-data/global-data-snapshot.json. Retrying in 5 seconds.                                                                  │_**

![image](https://user-images.githubusercontent.com/47939519/129199797-4f97992f-634d-4bba-8e11-3f46c39394c5.png)

it seems that _/data/humio-data_ is mounted as **read-only** on the _**auth**_ container.   but not on the _**humio**_ one. 
on inspection of the operator code... 
is it possible that line 206 of the
https://github.com/humio/humio-operator/blob/438d06c4bd61f782d9054b716a839aca311b2130/controllers/humiocluster_pods.go
is wrong?  it seem to force read-only on that auth container..

...
```
					VolumeMounts: []corev1.VolumeMount{
						{
							Name:      "humio-data",
							MountPath: humioDataPath,
							ReadOnly:  true,
```

**Comment by SaaldjorMike** [comment]
It is by design that the auth sidecar can only read messages from the data directory. The idea is that the Humio container writes files into its data directory, and then the auth container can read some files to set up credentials for the operator to use.

The more interesting thing would be to dig into the logs from the humio container and see why it hasn't written data into it.

**Comment by MarioSchuerewegen** [comment]
ah.  thats interesting :-)  i thought the auth was making that file..

does this help

**oc logs -f humiocluster-core-zexauj -n humio-logging -c humio**

`mkdir: cannot create directory ‘/data/logs’: Read-only file system
{"message":"2021-08-12T13:06:27.154+0000 [main] INFO  c.h.m.ServerRunner$ -1 - Starting Humio pid=1","@timestamp":1628773587154,"class":"c.h.m.ServerRunner$","thread":"main","loglevel":"INFO","kind":"logs","vhost":"-1"}
{"message":"2021-08-12T13:06:28.063+0000 [main] INFO  c.h.k.KafkaAdminUtils -1 - creating kafka admin client: client-reason='setupKafkaQueue' properties={metadata.max.age.ms=10000, bootstrap.servers=humio-cluster-kafka-bootstrap.humio-logging.svc:9092}","@timestamp":1628773588063,"class":"c.h.k.KafkaAdminUtils","thread":"main","loglevel":"INFO","kind":"logs","vhost":"-1"}
{"message":"2021-08-12T13:06:28.084+0000 [main] INFO  o.a.k.c.a.AdminClientConfig -1 - AdminClientConfig values: \n\tbootstrap.servers = [humio-cluster-kafka-bootstrap.humio-logging.svc:9092]\n\tclient.dns.lookup = use_all_dns_ips\n\tclient.id = \n\tconnections.max.idle.ms = 300000\n\tdefault.api.timeout.ms = 60000\n\tmetadata.max.age.ms = 10000\n\tmetric.reporters = []\n\tmetrics.num.samples = 2\n\tmetrics.recording.level = INFO\n\tmetrics.sample.window.ms = 30000\n\treceive.buffer.bytes = 65536\n\treconnect.backoff.max.ms = 1000\n\treconnect.backoff.ms = 50\n\trequest.timeout.ms = 30000\n\tretries = 2147483647\n\tretry.backoff.ms = 100\n\tsasl.client.callback.handler.class = null\n\tsasl.jaas.config = null\n\tsasl.kerberos.kinit.cmd = /usr/bin/kinit\n\tsasl.kerberos.min.time.before.relogin = 60000\n\tsasl.kerberos.service.name = null\n\tsasl.kerberos.ticket.renew.jitter = 0.05\n\tsasl.kerberos.ticket.renew.window.factor = 0.8\n\tsasl.login.callback.handler.class = null\n\tsasl.login.class = null\n\tsasl.login.refresh.buffer.seconds = 300\n\tsasl.login.refresh.min.period.seconds = 60\n\tsasl.login.refresh.window.factor = 0.8\n\tsasl.login.refresh.window.jitter = 0.05\n\tsasl.mechanism = GSSAPI\n\tsecurity.protocol = PLAINTEXT\n\tsecurity.providers = null\n\tsend.buffer.bytes = 131072\n\tssl.cipher.suites = null\n\tssl.enabled.protocols = [TLSv1.2, TLSv1.3]\n\tssl.endpoint.identification.algorithm = https\n\tssl.engine.factory.class = null\n\tssl.key.password = null\n\tssl.keymanager.algorithm = SunX509\n\tssl.keystore.location = null\n\tssl.keystore.password = null\n\tssl.keystore.type = JKS\n\tssl.protocol = TLSv1.3\n\tssl.provider = null\n\tssl.secure.random.implementation = null\n\tssl.trustmanager.algorithm = PKIX\n\tssl.truststore.location = null\n\tssl.truststore.password = null\n\tssl.truststore.type = JKS\n","@timestamp":1628773588084,"class":"o.a.k.c.a.AdminClientConfig","thread":"main","loglevel":"INFO","kind":"logs","vhost":"-1"}
{"message":"2021-08-12T13:06:28.142+0000 [main] INFO  o.a.k.c.u.AppInfoParser -1 - Kafka version: 2.6.0","@timestamp":1628773588142,"class":"o.a.k.c.u.AppInfoParser","thread":"main","loglevel":"INFO","kind":"logs","vhost":"-1"}
{"message":"2021-08-12T13:06:28.143+0000 [main] INFO  o.a.k.c.u.AppInfoParser -1 - Kafka commitId: 62abe01bee039651","@timestamp":1628773588143,"class":"o.a.k.c.u.AppInfoParser","thread":"main","loglevel":"INFO","kind":"logs","vhost":"-1"}
{"message":"2021-08-12T13:06:28.143+0000 [main] INFO  o.a.k.c.u.AppInfoParser -1 - Kafka startTimeMs: 1628773588140","@timestamp":1628773588143,"class":"o.a.k.c.u.AppInfoParser","thread":"main","loglevel":"INFO","kind":"logs","vhost":"-1"}
{"message":"2021-08-12T13:06:58.146+0000 [kafka-admin-client-thread | adminclient-1] INFO  o.a.k.c.a.i.AdminMetadataManager -1 - [AdminClient clientId=adminclient-1] Metadata update failed org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1628773618144, tries=74, nextAllowedTryMs=1628773618245) timed out at 1628773618145 after 74 attempt(s)\nCaused by: org.apache.kafka.common.errors.DisconnectException: Cancelled fetchMetadata request with correlation id 147 due to node -1 being disconnected\n","@timestamp":1628773618146,"class":"o.a.k.c.a.i.AdminMetadataManager org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1628773618144, tries=74, nextAllowedTryMs=1628773618245) timed out at 1628773618145 after 74 attempt(s)\nCaused by: org.apache.kafka.common.errors.DisconnectException: Cancelled fetchMetadata request with correlation id 147 due to node -1 being disconnected\n","thread":"kafka-admin-client-thread | adminclient-1","loglevel":"INFO","kind":"logs","vhost":"-1"}
{"message":"2021-08-12T13:07:28.146+0000 [kafka-admin-client-thread | adminclient-1] INFO  o.a.k.c.a.i.AdminMetadataManager -1 - [AdminClient clientId=adminclient-1] Metadata update failed org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1628773648145, tries=75, nextAllowedTryMs=1628773648246) timed out at 1628773648146 after 75 attempt(s)\nCaused by: org.apache.kafka.common.errors.DisconnectException: Cancelled fetchMetadata request with correlation id 297 due to node -1 being disconnected\n","@timestamp":1628773648146,"class":"o.a.k.c.a.i.AdminMetadataManager org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1628773648145, tries=75, nextAllowedTryMs=1628773648246) timed out at 1628773648146 after 75 attempt(s)\nCaused by: org.apache.kafka.common.errors.DisconnectException: Cancelled fetchMetadata request with correlation id 297 due to node -1 being disconnected\n","thread":"kafka-admin-client-thread | adminclient-1","loglevel":"INFO","kind":"logs","vhost":"-1"}
{"message":"2021-08-12T13:07:28.148+0000 [main] WARN  c.h.k.KafkaAdminUtils -1 - Got exception fetching number of replicas for topic=global-events java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Call(callName=describeTopics, deadlineMs=1628773648146, tries=1, nextAllowedTryMs=1628773648247) timed out at 1628773648147 after 1 attempt(s)\n\tat org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45) ~[humio-assembly.jar:0.1]\n\tat org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32) ~[humio-assembly.jar:0.1]\n\tat org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89) ~[humio-assembly.jar:0.1]\n\tat org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260) ~[humio-assembly.jar:0.1]\n\tat com.humio.kafka.KafkaAdminUtils.fetchTopicPartitionAssignments(KafkaAdminUtils.scala:124) ~[humio-assembly.jar:0.1]\n\tat com.humio.kafka.KafkaAdminUtils.createTopic(KafkaAdminUtils.scala:86) ~[humio-assembly.jar:0.1]\n\tat com.humio.kafka.GlobalKafka.$anonfun$setupKafkaQueues$1(Global.scala:132) ~[humio-assembly.jar:0.1]\n\tat com.humio.kafka.GlobalKafka.$anonfun$setupKafkaQueues$1$adapted(Global.scala:131) ~[humio-assembly.jar:0.1]\n\tat scala.util.Using$.resource(Using.scala:261) ~[humio-assembly.jar:0.1]\n\tat com.humio.kafka.GlobalKafka.setupKafkaQueues(Global.scala:131) ~[humio-assembly.jar:0.1]\n\tat com.humio.kafka.GlobalKafka.<init>(Global.scala:117) ~[humio-assembly.jar:0.1]\n\tat com.humio.kafka.GlobalKafka.<init>(Global.scala:102) ~[humio-assembly.jar:0.1]\n\tat com.humio.core.Config$.fromEnv(Config.scala:1475) ~[humio-assembly.jar:0.1]\n\tat com.humio.main.ServerRunner$.main(ServerRunner.scala:97) ~[humio-assembly.jar:0.1]\n\tat com.humio.main.ServerRunner.main(ServerRunner.scala) ~[humio-assembly.jar:0.1]\nCaused by: org.apache.kafka.common.errors.TimeoutException: Call(callName=describeTopics, deadlineMs=1628773648146, tries=1, nextAllowedTryMs=1628773648247) timed out at 1628773648147 after 1 attempt(s)\nCaused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.\n","@timestamp":1628773648148,"class":"c.h.k.KafkaAdminUtils java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Call(callName=describeTopics, deadlineMs=1628773648146, tries=1, nextAllowedTryMs=1628773648247) timed out at 1628773648147 after 1 attempt(s)\n\tat org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45) ~[humio-assembly.jar:0.1]\n\tat org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32) ~[humio-assembly.jar:0.1]\n\tat org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89) ~[humio-assembly.jar:0.1]\n\tat org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260) ~[humio-assembly.jar:0.1]\n\tat com.humio.kafka.KafkaAdminUtils.fetchTopicPartitionAssignments(KafkaAdminUtils.scala:124) ~[humio-assembly.jar:0.1]\n\tat com.humio.kafka.KafkaAdminUtils.createTopic(KafkaAdminUtils.scala:86) ~[humio-assembly.jar:0.1]\n\tat com.humio.kafka.GlobalKafka.$anonfun$setupKafkaQueues$1(Global.scala:132) ~[humio-assembly.jar:0.1]\n\tat com.humio.kafka.GlobalKafka.$anonfun$setupKafkaQueues$1$adapted(Global.scala:131) ~[humio-assembly.jar:0.1]\n\tat scala.util.Using$.resource(Using.scala:261) ~[humio-assembly.jar:0.1]\n\tat com.humio.kafka.GlobalKafka.setupKafkaQueues(Global.scala:131) ~[humio-assembly.jar:0.1]\n\tat com.humio.kafka.GlobalKafka.<init>(Global.scala:117) ~[humio-assembly.jar:0.1]\n\tat com.humio.kafka.GlobalKafka.<init>(Global.scala:102) ~[humio-assembly.jar:0.1]\n\tat com.humio.core.Config$.fromEnv(Config.scala:1475) ~[humio-assembly.jar:0.1]\n\tat com.humio.main.ServerRunner$.main(ServerRunner.scala:97) ~[humio-assembly.jar:0.1]\n\tat com.humio.main.ServerRunner.main(ServerRunner.scala) ~[humio-assembly.jar:0.1]\nCaused by: org.apache.kafka.common.errors.TimeoutException: Call(callName=describeTopics, deadlineMs=1628773648146, tries=1, nextAllowedTryMs=1628773648247) timed out at 1628773648147 after 1 attempt(s)\nCaused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.\n","thread":"main","loglevel":"WARN","kind":"logs","vhost":"-1"}
{"message":"2021-08-12T13:07:29.050+0000 [main] INFO  c.h.k.KafkaAdminUtils -1 - closing kafka admin client: client-reason='setupKafkaQueue'","@timestamp":1628773649050,"class":"c.h.k.KafkaAdminUtils","thread":"main","loglevel":"INFO","kind":"logs","vhost":"-1"}`

 **oc logs -f humiocluster-core-zexauj -n humio-logging -c init**
`Starting humio-operator-helper 0.4.0 (de5e2381747ee916fc31698ea6cfb115c89515bb on 2021-07-05T15:57:21+00:00)`

 **oc logs -f humiocluster-core-zexauj -n humio-logging -c auth**
`Starting humio-operator-helper 0.4.0 (de5e2381747ee916fc31698ea6cfb115c89515bb on 2021-07-05T15:57:21+00:00)
Waiting on the Humio container to create the files /data/humio-data/local-admin-token.txt and /data/humio-data/global-data-snapshot.json. Retrying in 5 seconds.
Waiting on the Humio container to create the files /data/humio-data/local-admin-token.txt and /data/humio-data/global-data-snapshot.json. Retrying in 5 seconds.
Waiting on the Humio container to create the files /data/humio-data/local-admin-token.txt and /data/humio-data/global-data-snapshot.json. Retrying in 5 seconds.
`

or should i look for the error in the operator pod ?

**Comment by MarioSchuerewegen** [comment]
just noticed something
`humio mkdir: cannot create directory ‘/data/logs’: Read-only file system   `

there is no volume automounted on  /data   so how can he create a directory there..

![image](https://user-images.githubusercontent.com/47939519/129206519-43199c7d-32fa-4683-9368-fb0ffdc85250.png)

**Comment by MarioSchuerewegen** [comment]
never mind.  this is all a red herring..  

real problem is here

` kafka 2021-08-12 14:46:58,993 INFO [SocketServer brokerId=0] Failed authentication with /10.130.3.69 (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector) [data-plane-kafka-n │`
