### ISSUE TITLE
Setting CSP headers while deploying

### ISSUE THREAD

**Issue by ravi-kumar-quo** [humio/humio-operator#546]
Hi I have been trying to set custom content-security-policy headers while deploying the cluster

**Comment by SaaldjorMike** [comment]
LogScale have support for the environment variable [STATIC_IMAGE_CONTENT_URL](https://library.humio.com/falcon-logscale-self-hosted/envar-static-image-content-url.html) if that is what you're asking for. If that does not fit your needs, you can likely leverage features of whatever ingress controller you have in front of LogScale to override CSP headers.

**Comment by SaaldjorMike** [comment]
Closing. Feel free to reopen with more details.
