### ISSUE TITLE
Too long CRD definition

### ISSUE THREAD

**Issue by nevosial** [humio/humio-operator#553]
While trying to deploy the helm chart for operator version 0.14.1 via spinnaker , the deploy fails with the following message

`Deploy failed: The CustomResourceDefinition "humioclusters.core.humio.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

**Comment by schofield** [comment]
@nevosial The --server-side flag is now required when running kubectl apply on the HumioCluster CRD due to its size. 

https://library.humio.com/preview/docs/installation/containers/kubernetes/kubernetes-operator-upgrade/#version-0-14-0
