### ISSUE TITLE
Stuck in reconcile loop due to mismatch in HumioRepository ingestSizeInGB 

### ISSUE THREAD

**Issue by jayadeepkmct** [humio/humio-operator#569]
When we set `ingestSizeInGB` as 0 in `HumioRepository` to let humio cloud decide the default value for this field, Humio operator keeps trying to reset it to 0.

Example logs

```json
{"level":"info","ts":"2022-02-21T04:20:41.293027198Z","caller":"controllers/humiorepository_controller.go:162","func":"github.com/humio/humio-operator/controllers.(*HumioRepositoryReconciler).Reconcile","msg":"repository information differs, triggering update, expected [REPONAME]/7/0/0, got [REPONAME]/7/25200/0","Operator.Commit":"716bb207b4d2a4305e198e1978c4100f600a787a","Operator.Date":"2021-11-09T21:43:02+00:00","Operator.Version":"0.13.0","Request.Namespace":"humio","Request.Name":"REPONAME","Request.Type":"HumioRepositoryReconciler","Reconcile.ID":"vmcrfw"}
```

**Comment by namm2** [comment]
@jayadeepkmct Can you tried without setting `ingestSizeInGB` as 0? IMO this field should be omitted if you want to use the default value. Set it to 0 for default value is counter-intuitive.

**Comment by jayadeepkmct** [comment]
That doesn't work either.
As per the code here https://github.com/humio/humio-operator/blob/85bed4456d6eb580d655ad462afad1ec6e6aef22/api/v1alpha1/humiorepository_types.go#L38
`ingestSizeInGB` is not an optional field. Type should be `*int32` otherwise.  So it would be set to 0 even if you omit the field in the spec.

And in the controller,
https://github.com/humio/humio-operator/blob/85bed4456d6eb580d655ad462afad1ec6e6aef22/controllers/humiorepository_controller.go#L157
It is explicitly checking if the ingestsize in the spec is matching with that in the actual repo. So if we omit this field or set it to zero, the reconciler will always get true in this comparison and it will keep trying to update the size to 0.

**Comment by jayadeepkmct** [comment]
Currently humio cloud sets the value of ingestSizeInGB as 0 for unlimited. Hence this issue is not valid anymore.
