### ISSUE TITLE
Feature Request: Improve ZONE variable use

### ISSUE THREAD

**Issue by ryanfaircloth** [humio/humio-operator#592]
Instead of current method use the downward api
https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/

**Comment by SaaldjorMike** [comment]
This isn't as easy as it seems. We need to inject the zone metadata from the `node` object to the Humio pod, while what you link to makes it possible to inject metadata _from the pod object_ itself. When creating pods we don't necessarily know what host we will get scheduled to, which impacts what zone the pod ends up in.

Maybe I'm missing something, if so, let me know. I really wish we didn't have the current implementation, but this was the "best" I could come up with.

**Comment by ryanfaircloth** [comment]
@SaaldjorMike the link provided is simply another way to get the same value to avoid the exec process

**Comment by SaaldjorMike** [comment]
What we do today is:
1. Create pod with an init container
2. Init container gets the k8s worker name injected so it knows "where it landed" after scheduling
3. The init container talks to k8s API Server and fetches the zone/failuredomain information from the k8s node object labels which writes it to a shared volume and then the init container exits
4. The humio container starts up and mounts the same shared volume with info on zone from the k8s worker node label, then starts up Humio which sets this ZONE env var.

**Comment by ryanfaircloth** [comment]
Going to close this, thats about as good as it gets thank you
