### ISSUE TITLE
Drift Between Helper Image Version in Helper Source vs Version Operator Uses

### ISSUE THREAD

**Issue by kebroad** [humio/humio-operator#642]
For operator version 0.16.0, It looks like the operator is deploying pods with the default helper image version defined [here](https://github.com/humio/humio-operator/blob/operator-0.16.0/controllers/humiocluster_defaults.go#L37) in a go constant:
```
HelperImage                  = "humio/humio-operator-helper:85bed4456d6eb580d655ad462afad1ec6e6aef22"`
```

However, in the [helper source,](https://github.com/humio/humio-operator/blob/operator-0.16.0/images/helper/version.go#L20) it has a differing version:
```
Version = "0.5.0"
```

It seems like your github action is using the latter as the helper image tag when a release is run [here](https://github.com/humio/humio-operator/blob/master/.github/workflows/release-container-helperimage.yaml#L16).

If we were to build the helper image from source ourselves, with operator version being an input, which source of truth should we pick that would be the most compatible with the operator and humio-core pods? 

I would assume the first, as if we want the operator to deploy it, it would have to match that version.

**Comment by SaaldjorMike** [comment]
Hi. Thanks for letting us know.

We decided a while ago that we wouldn't need to version the helper container similar to how we do it for the operator itself and then just rely on the "commit SHA tag" for the helper image which gets built upon merge to master, and is pushed here: https://github.com/humio/humio-operator/blob/master/.github/workflows/master.yaml#L87

We should probably on the other hand update the helper source code with some other placeholder than `0.5.0` as that doesn't really align with the decision to not version it that way, which makes it a bit confusing. This would also mean that the workflow for pushing a new `x.y.z`-style tag is going away: https://github.com/humio/humio-operator/blob/master/.github/workflows/release-container-helperimage.yaml

**Comment by kebroad** [comment]
Thanks for clearing that up! We will use a command similar to below when fetching the right helper image version, given operator_version as input:

`git ls-remote https://github.com/humio/humio-operator.git --tags "humio-operator-${operator_version}" | awk  '{print $1}'`

Closing this issue.
