### ISSUE TITLE
Auto remove nodes

### ISSUE THREAD

**Issue by ryanfaircloth** [humio/humio-operator#660]
Operator should check the current known cluster nodes against the pods API and remove any pods that have terminated. Any pods that exist regardless of health state should remain. This will keep the cluster admin ui clean when nodes are naturally replaced such as after an upgrade
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/35384120/217311427-0b18de93-366f-4b1b-8d35-e918eaf8a030.png">

**Comment by jswoods** [comment]
As of Logscale 1.70, the new vhost selection feature cleans up old nodes automatically after 2 hours if they don't hold any segments.

A node shouldn't end up in this state after typical upgrades or restarts, only when the volume backing the pod is removed.

Closing as we're relying on Logscale to do the node cleanup.
