### ISSUE TITLE
Release notes/change logs

### ISSUE THREAD

**Issue by brads-au** [humio/humio-operator#700]
Hi, it is possible to get release notes/change logs on the new Operator releases? It would be great to see what has been added/fixed without going through the commit history. Thanks.

**Comment by SaaldjorMike** [comment]
Release notes can be found here: https://library.humio.com/falcon-logscale/installation-kubernetes-operator-upgrade.html#installation-containers-kubernetes-operator-upgrade-notes

I see that the releases here on github doesn't link to that, so I'll make sure we add a link to it from here.
