### ISSUE TITLE
HumioCluster ingressClassName

### ISSUE THREAD

**Issue by EhsanLunar** [humio/humio-operator#709]
As the `kubernetes.io/ingress.class: nginx` is deprecated is there a plan to get `ingressClassName` support in the `HumioCluster` CRD?

Same as https://github.com/humio/humio-operator/issues/319 I guess, which hasn't been touched since 2021 and no responses...

**Comment by SaaldjorMike** [comment]
Closing due to duplicate of https://github.com/humio/humio-operator/issues/319
I know the other one has not seen any activity, but that doesn't mean we should have more issues tracking the same thing.
