### ISSUE TITLE
K8s Compatibility Issue

### ISSUE THREAD

**Issue by Manikanth06** [humio/humio-operator#718]
Hi @jswoods. Is  this (humio/humio-operator:0.10.1.patch.2023-08-23.1) compatible with the Kubernetes-1.18 as this compatibility is crucial.

**Comment by SohilShri** [comment]
@jswoods I am working with @Manikanth06 

This is our Infra of Humio: 

Infra type: Self Hosted (Operator based) 
K8s version: 1.18
Humio Version: 1.34.2 
Humio Operator: 0.10.1 

We are looking for a any official version released of humio operator which will have the CVE fixes, which was reported ton (https://github.com/humio/humio-operator/issues/715)

The next version we can see in the humio official document is 0.10.2 as per this matrix: 
https://library.humio.com/falcon-logscale-self-hosted/installation-kubernetes-operator-upgrade.html#installation-kubernetes-operator-versions

**Comment by jswoods** [comment]
Yes, the humio/humio-operator:0.10.1.patch.2023-08-23.1 patch is compatible with Kubernetes 1.18.

**Comment by Manikanth06** [comment]
@jswoods, but we couldn't find  this release version in official site, and also you mentioned it as single time patch, is this version has support from Crowdstrike? Could you please confirm?

**Comment by jswoods** [comment]
It's not listed on the release list as we technically do not release patches for versions this old. We will however support this version for you to the same degree we'd support 0.10.1. I do suggest moving to later versions of the operator once you've upgraded to k8s 1.19 or later. Additionally I also suggest upgrading to a more recent version of humio.
