### ISSUE TITLE
humioServiceAccountAnnotations should be applied on role creation

### ISSUE THREAD

**Issue by L1ghtman2k** [humio/humio-operator#740]
We are running into a chicken and egg problem when bootstrapping a humio cluster that relies on role annotations for IRSA.

humioServiceAccountAnnotations are only set on reconcile/update of the cluster, but reconciliation fails early because the cluster is never brought up. The cluster intern is never brought up because the annotations providing IRSA role (for access to MSK/S3) are missing.

This would be resolved if initial creation of the role also included annotations inside humioServiceAccountAnnotations

**Comment by SaaldjorMike** [comment]
Not quite sure I fully follow here, but here's what I found:

The code creates a new service account before spinning up cluster pods, and this new service account includes any user-specific annotations. After creating that service account, it continues to create cluster pods, so the annotation should be there without a bootstrapping issue as you describe.

The service account is created here: https://github.com/humio/humio-operator/blob/0082e7d546bc9c8a8c7070916c9082fe06949921/controllers/humiocluster_controller.go#L804
and as you may see, we pass in the user-defined service account annotations to https://github.com/humio/humio-operator/blob/0082e7d546bc9c8a8c7070916c9082fe06949921/controllers/humiocluster_controller.go#L1208 which puts those annotations into the `ServiceAccount` object we construct and create: https://github.com/humio/humio-operator/blob/0082e7d546bc9c8a8c7070916c9082fe06949921/pkg/kubernetes/service_accounts.go#L36

I did stumble upon some logic to update service account annotations _prior_ to the service account creation, and this obviously makes no sense and should be the other way around, so we don't try updating something that may not yet exist, which would throw an error and fail the reconcile. When reading your message this doesn't sound like what you are being hit by though.

**Comment by L1ghtman2k** [comment]
https://github.com/humio/humio-operator/blob/0082e7d546bc9c8a8c7070916c9082fe06949921/controllers/suite/common.go#L287 is the call I was referencing

**Comment by SaaldjorMike** [comment]
True, anything in `controllers/suite/...` is test-related.
It is technically possible to configure the same service account for all 3 containers (init,humio,auth), but not recommended. Init container needs to leverage k8s api to obtain zone-information for the k8s worker node the pod is on, and auth container needs to create/update a k8s secret with a token in it. The "humio" container does not need any of that, and it is better to keep things split up to only grant the minimal set of permissions required for each of the containers.
