### ISSUE TITLE
Configmap <cluster_name>-extra-kafka-configs not being reconciled when changing /extraKafkaConfigs

### ISSUE THREAD

**Issue by yenoromm** [humio/humio-operator#798]
**Issue:**
When changing `extraKafkaConfigs` for a humiocluster CR after creation, the configmap doesn't get updated.

**Expected:**
When updating the `extraKafkaConfigs `for a humiocluster CR, configmap will always be reconciled to the the latest value specified.

**Comment by SaaldjorMike** [comment]
Duplicate of https://github.com/humio/humio-operator/issues/764. Closing.
