### ISSUE TITLE
Add support for new Alert Types

### ISSUE THREAD

**Issue by togie6** [humio/humio-operator#800]
We have recently been advised to use alternative alerting functionality within Logscale. 

However this is quite a problem as the Humio Operator does not currently support
- Scheduled Alerts
  - https://schemas.humio.com/scheduledSearch/v0.1.0
  - https://library.humio.com/data-analysis/automated-scheduled-searches.html
- Filter Alerts
  - https://schemas.humio.com/filterAlert/v0.1.0
  - https://library.humio.com/data-analysis/automated-alerts-single.html

Could the operator please be updated to support this new functionality. We use the Humio operator along with Argo to ensure our alerts are deployed and in the correct state within a large scale environment.

**Comment by jswoods** [comment]
Support for Filter Alerts has been added. Scheduled Alerts are still pending.

**Comment by SaaldjorMike** [comment]
Support for scheduled searches and aggregate alerts have been merged in and both of them will be part of the next operator release.
