### ISSUE TITLE
Feature request: Specify the default sidecar image to use with the operator

### ISSUE THREAD

**Issue by yenoromm** [humio/humio-operator#844]
Right now when creating a humio cluster CR and do not supply a sidecar image, it uses the default hardcoded image value in the operator. Similar to the Strimzi operator, we would like to see default images being able to set in the helm chart values of the operator rather than specifying with each humio cluster

**Comment by SaaldjorMike** [comment]
Fixed by https://github.com/humio/humio-operator/pull/849
