### ISSUE TITLE
Add support for OpenShift Route's

### ISSUE THREAD

**Issue by SaaldjorMike** [humio/humio-operator#91]
Maybe auto-detect if it is openshift? Or, just use a flag to enable it similar to nginx ingress?

**Comment by zach-robinson** [comment]
Meeting notes: It may be possible to install the [router operator](https://github.com/openshift/router) into Kind to enable an easy method for testing. We would like for this to be implemented by the end of 1Q 2021 to support our integration use-cases if at all possible.

**Comment by zach-robinson** [comment]
@SaaldjorMike Any update on this one?

**Comment by SaaldjorMike** [comment]
@zach-robinson Unfortunately not.
